sudo: required
dist: trusty
language: cpp
cache: apt

branches:
  only:
    - 'master'

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install pkg-config libopencv-dev

script:
  - cd linux && make

after_success:  
  - ../example/fit -m ../example/my68-1d.amf -h ../example/haarcascade_frontalface_alt2.xml -i ../example/multipeople.jpg 
  - ../example/fit -m ../example/my68-1d.amf -h ../example/haarcascade_frontalface_alt2.xml -v ../example/seq1.avi -n 24
